name: Run E2E Tests

on:
  push:
    branches:
      - "*"
jobs:
  chrome:
    name: E2E tests for Chrome
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browserVersion: [stable, beta, canary]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "9.8"
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: |
          echo "BROWSER_VERSION=${{ matrix.browserVersion }}" >> $GITHUB_ENV
      - run: pnpm wdio
